CREATE DATABASE  InLock_Games_Manha;

USE InLock_Games_Manha;


CREATE TABLE Estudios(
IdEstudio INT PRIMARY KEY IDENTITY,
NomeEstudio  VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE TipoUsuario(
IdTipoUsuario INT PRIMARY KEY IDENTITY,
Titulo  VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Usuarios(
IdUsuario INT PRIMARY KEY IDENTITY,
Email VARCHAR(150) NOT NULL UNIQUE,
Senha VARCHAR(50) NOT NULL,
IdTipoUsuario  INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario)
);


CREATE TABLE Jogos(
IdJogo INT PRIMARY KEY IDENTITY,
Nome  VARCHAR(100) NOT NULL,
Descricao VARCHAR(700) NOT NULL,
DataLancamento DATE NOT NULL,
Valor  MONEY NOT NUll,
IdEstudio INT FOREIGN KEY REFERENCES Estudios(IdEstudio)
);

